
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: hello-helmchart
  namespace: default
spec:
  interval: 10m
  chart: ./cloud-interview/apps/charts/hello
  sourceRef:
    kind: GitRepository
    name: hello

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: hello
  namespace: default
spec:
  interval: 10m
  values:
    replicaCount: 5
  chartRef:
    kind: HelmChart
    name: hello-helmchart
    namespace: default
