
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: hello
  namespace: default
spec:
  interval: 5m0s
  url: https://github.com/franck-art/ornikar-test
  ref:
    branch: master
    