---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: hello
  namespace: default
spec:
  interval: 1m
  timeout: 2m
  chart:
    spec:
      chart: ./cloud-interview/apps/charts/hello
      version: '0.1.1'
      sourceRef:
        kind: HelmRepository
        name: hello
      interval: 5m
  releaseName: hello-franck
  targetNamespace: hello
  values:
    replicaCount: 5
  